export default [
  {
    id: 1,
    name: "Laurence Llewelyn Bowen",
    profileImg: "user-img-2.png",
    location: "Leeds, UK",
    job: "Corporate Hinderance and Quality Control for the European and...",
    company: "Microsoft Global Software",
    rank: "Superhost",
    rankNum: "/5219",
  },
  {
    id: 2,
    name: "Florence Banniester",
    profileImg: "user-img-3.png",
    location: "Leeds, UK",
    job: "Corporate Hinderance and Quality Control for the European and...",
    company: "Microsoft Global Software",
    rank: "Newbie",
    rankNum: "/40",
  },
  {
    id: 3,
    name: "Miriam Cooper",
    profileImg: "user-img-4.png",
    location: "Leeds, UK",
    job: "Corporate Hinderance and Quality Control for the European and...",
    company: "Microsoft Global Software",
    rank: "Superhost",
    rankNum: "/5219",
  },
  {
    id: 4,
    name: "Danny Bloom",
    profileImg: "user-img-2.png",
    location: "Leeds, UK",
    job: "Corporate Hinderance and Quality Control for the European and...",
    company: "Microsoft Global Software",
    rank: "Newbie",
    rankNum: "/40",
  },
  {
    id: 5,
    name: "Alessandro Pietro",
    profileImg: "user-img-3.png",
    location: "Leeds, UK",
    job: "Corporate Hinderance and Quality Control for the European and...",
    company: "Microsoft Global Software",
    rank: "Superhost",
    rankNum: "/5219",
  },
  {
    id: 6,
    name: "Bertina Sanchez",
    profileImg: "user-img-4.png",
    location: "Leeds, UK",
    job: "Corporate Hinderance and Quality Control for the European and...",
    company: "Microsoft Global Software",
    rank: "Superhost",
    rankNum: "/5219",
  },
];
