export default [
  {
    id: 1,
    meetingImg: "tile-img-2.png",
    title:
      "Artificial intelligence and the future home experience this the future home experience",
    date: "Tues 29th Sept / 1 - 2pm",
    spaces: "1 of 3 spaces available",
    flair: "Leeds Digital Festival",
    host: "Laurence Llewelyn Bowen",
    hostImg: "user-img-1.png",
    hostType: "Superhost /5219",
  },
  {
    id: 2,
    meetingImg: "tile-img-1.png",
    title: "AI - the code of codes - but which code",
    date: "Tues 29th Sept / 1 - 2pm",
    spaces: "1 of 3 spaces available",
    flair: "Leeds Digital Festival",
    host: "Laurence Llewelyn Bowen",
    hostImg: "user-img-1.png",
    hostType: "Superhost /5219",
  },
  {
    id: 3,
    meetingImg: "tile-img-3.png",
    title: "AI - the code of codes - but which code",
    date: "Multiple times available",
    spaces: "Check spaces available",
    flair: "",
    host: "Laurence Llewelyn Bowen",
    hostImg: "user-img-1.png",
    hostType: "Superhost /5219",
  },
  {
    id: 4,
    meetingImg: "tile-img-4.png",
    title: "Could AI kill the design industry?",
    date: "Multiple times available",
    spaces: "Check spaces available",
    flair: "Leeds Digital Festival",
    host: "Laurence Llewelyn Bowen",
    hostImg: "user-img-1.png",
    hostType: "Superhost /5219",
  },
];
